export const mySkills = [
  { id: 1, img: "/projects-card-img.jpg", title: "HTML 5" },
  { id: 2, img: "/projects-card-img.jpg", title: "CSS 3" },
  { id: 3, img: "/projects-card-img.jpg", title: "JavaScript" },
  { id: 4, img: "/projects-card-img.jpg", title: "TypeScript" },
  { id: 5, img: "/projects-card-img.jpg", title: "React JS" },
  { id: 6, img: "/projects-card-img.jpg", title: "Next JS" },
  { id: 7, img: "/projects-card-img.jpg", title: "Node JS" },
  { id: 8, img: "/projects-card-img.jpg", title: "Express JS" },
  { id: 9, img: "/projects-card-img.jpg", title: "Nest JS" },
  { id: 10, img: "/projects-card-img.jpg", title: "Mongo DB" },
  { id: 11, img: "/projects-card-img.jpg", title: "Postgre SQL" },
  { id: 12, img: "/projects-card-img.jpg", title: "Bootstrap" },
  { id: 13, img: "/projects-card-img.jpg", title: "Tailwind CSS" },
  { id: 14, img: "/projects-card-img.jpg", title: "GraphQL" },
  { id: 15, img: "/projects-card-img.jpg", title: "RESTFul API" },
  { id: 16, img: "/projects-card-img.jpg", title: "Git" },
  { id: 17, img: "/projects-card-img.jpg", title: "Sass" },
  { id: 18, img: "/projects-card-img.jpg", title: "React Native" },
  { id: 19, img: "/projects-card-img.jpg", title: "Vue JS" },
  { id: 20, img: "/projects-card-img.jpg", title: "Angular" },
];

export const myProjects = [
  {
    id: 1,
    title: "School Management Frontend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: ["Next JS", "Tailwind CSS"],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 2,
    title: "School Management Backend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: ["Nest JS", "GraphQL"],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 3,
    title: "Event Management Frontend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 4,
    title: "Event Management Backend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 5,
    title: "Flight Booking Frontend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 6,
    title: "Flight Booking Backend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 7,
    title: "Food Delivery Frontend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 8,
    title: "Food Delivery Backend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 9,
    title: "Next Nest Chat Frontend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 10,
    title: "Next Nest Chat Backend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 11,
    title: "Project Management Frontend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
  {
    id: 12,
    title: "Project Management Backend",
    desc: "",
    type: "",
    img: "/projects-card-img.jpg",
    technologyUsed: [],
    live: {
      icon: "",
      link: "",
    },
    github: {
      icon: "",
      link: "",
    },
  },
];
